### ISSUE TITLE
Working with projects

### ISSUE THREAD

**Issue by sigul** [maxjacobson/github-pages-editorial#1]
Hi,
I tested the workflow with a project Jekyll blog (sigul.github.io/jekyll) but, it didn't work.

**Comment by maxjacobson** [comment]
hey @sigul!

Will you provide more details on what you tried and what behavior you observed?

**Comment by sigul** [comment]
Hi,
I did set repo to sigul.github.io/Jekyll/ and it didn't work

Then I tried to set it to sigul.github.io and name the post /jellylike/_post/data-post-name.md

Tried to add http://

I got an error it didn't work, without any other notice of error

**Comment by sigul** [comment]
I am just a newbie in this things, so I could have had a problem wit the token. I just generated the one suggested by github

**Comment by maxjacobson** [comment]
hey, no worries, I'm a newbie too :smile: 

I think I know what your issue is.

You should either (pick one):

1. rename your repo from "jekyll" to "sigul.github.io" here: https://github.com/sigul/jekyll/settings
1. configure the workflow to update the repo called "jekyll", not "sigul.github.io"

**Comment by sigul** [comment]
Glad to know :)

Unfortunately, solution 2 didn't work. I am just creating a blog to test all the feature I need before to migrate my blog. I want to use project because it would allow me to have more than one site under my account. 

Was wondering if it could be related to this line

endpoint = "/repos/" + path_to_repo + "/contents/" + path_to_file

I tried to delete "/contents/" but nothing changed.

**Comment by maxjacobson** [comment]
ah, now I understand what you mean by project!

I think we need to keep "/contents/". We're using this API endpoint to create the file: https://developer.github.com/v3/repos/contents/#create-a-file

when the API request works, it responds with a status of 201 Created. When it responds with any other status, the workflow prints out the response from the server, which probably provides a clue about what's going on. Are you seeing any logged output?

**Comment by sigul** [comment]
No, just a message of error

**Comment by maxjacobson** [comment]
Will you send a screenshot?

**Comment by sigul** [comment]
Do you mean like this? Maybe I Caen provide more useful details, just ask for them.

![image](https://cloud.githubusercontent.com/assets/7622916/8273358/335fe8d4-186a-11e5-8292-ff8722f34de6.jpg)
![image](https://cloud.githubusercontent.com/assets/7622916/8273359/33638bf6-186a-11e5-87ea-0bbf05d1e3c2.jpg)

**Comment by sigul** [comment]
Another info that could help. My website is published on a gh-pages branch

**Comment by maxjacobson** [comment]
Thanks for the info. I'll see if I can reproduce it sometime this week maybe!

**Comment by maxjacobson** [comment]
![image](https://cloud.githubusercontent.com/assets/1421211/8281607/9e7b64ac-18b7-11e5-8a87-e66ef3d34132.jpg)

https://github.com/maxjacobson/test-project-sigul/blob/gh-pages/_posts/2015-06-22-some-post.md

Well... It seems to work for me :/

**Comment by sigul** [comment]
now it works also for me, I just tested it on my iPhone. but yesterday it was not working nor on my iPhone nor on my iPad. I will test it again this evening, this is very strange. it could be related to the token I generated. will let you know if I find something relevant. thanks for supporting

**Comment by maxjacobson** [comment]
My pleasure, glad it's working now

I'll close it now but feel free to reopen if something else comes up :)
