### ISSUE TITLE
Access token permissions

### ISSUE THREAD

**Issue by danielhoherd** [maxjacobson/github-pages-editorial#2]
The tutorial doesn't indicate which permissions are needed for the access token. It would be nice to know this so as to not give it more than it needs.

**Comment by maxjacobson** [comment]
Totally agree. I haven't really experimented with it. Do you want to investigate?

**Comment by danielhoherd** [comment]
I configured a token with only repo and it worked fine.

**Comment by maxjacobson** [comment]
Updated the post via https://github.com/hardscrabble/hardscrabble.github.io/commit/d718007049f6d64cdcceb3650bb95197878cba12

Thanks for investigating @danielhoherd :smile:
