### ISSUE TITLE
It would be cool to make a workflow that lets you edit existing posts

### ISSUE THREAD

**Issue by maxjacobson** [maxjacobson/github-pages-editorial#3]
https://twitter.com/nashp/status/585914661419253761

It should be doable. Probably it would be a separate-but-similar workflow

**Comment by lewislepton** [comment]
i just this minute got this workflow from wordpress moons ago, to then just html to now jekyll. i lke the simplicity, plus love this workflow since i use editorial.

thanks for making it. i yes, id love that feature as well ;)

but just to say 'thanks' more than anything ;)

**Comment by maxjacobson** [comment]
Glad you like it @lewislepton :)
